@baseUrl = http://localhost:3001
@validMovieId = 69f914629c3dfa49b90ea756
@missingMovieId = 000000000000000000000000
@invalidMovieId = dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Obtener todas las peliculas
GET {{baseUrl}}/movies

### Filtrar por genero
GET {{baseUrl}}/movies?genre=Comedy

### Obtener una pelicula por id valido
GET {{baseUrl}}/movies/{{validMovieId}}

### Excepcion: id con formato invalido
GET {{baseUrl}}/movies/{{invalidMovieId}}

### Excepcion: id valido pero inexistente
GET {{baseUrl}}/movies/{{missingMovieId}}

### Crear una pelicula valida
POST {{baseUrl}}/movies
Content-Type: application/json

{
    "title": "Pillo",
    "year": 2020,
    "director": "John Doe",
    "duration": 120,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": ["Adventure", "Comedy"]
}

### Excepcion: crear una pelicula invalida
POST {{baseUrl}}/movies
Content-Type: application/json

{
    "title": "",
    "year": 1800,
    "director": "John Doe",
    "duration": -10,
    "poster": "not-a-valid-url",
    "genre": ["action"]
}

### Actualizar una pelicula valida
PATCH {{baseUrl}}/movies/{{validMovieId}}
Content-Type: application/json

{
    "title": "test",
    "year": 2020

}

### Excepcion: actualizar con id invalido
PATCH {{baseUrl}}/movies/{{invalidMovieId}}
Content-Type: application/json

{
    "title": "test"
}

### Excepcion: actualizar con id inexistente
PATCH {{baseUrl}}/movies/{{missingMovieId}}
Content-Type: application/json

{
    "title": "test"
}

### Eliminar una pelicula valida
DELETE {{baseUrl}}/movies/{{validMovieId}}

### Excepcion: eliminar con id invalido
DELETE {{baseUrl}}/movies/{{invalidMovieId}}

### Excepcion: eliminar con id inexistente
DELETE {{baseUrl}}/movies/{{missingMovieId}}